# -*- coding: utf-8 -*-
"""translate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/160mjGCch6GJu9N-vAEECL-IMylbd2K8S
"""

from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd

df_test = pd.read_csv('/content/drive/MyDrive/machine translation/input/spanish.csv')

df_test_update = df_test_update.drop(['translate'], axis=1)

df_test_update

#!pip install googletrans==3.1.0a0

from googletrans import Translator

translator = Translator(service_urls=['translate.googleapis.com'])

#from_lang = 'ko'
#from_lang = 'ru'
#from_lang = 'ja'
from_lang = 'es'
to_lang = 'en'

translated = []
for get_sentence in df_test_update['tweet']:
  text_to_translate = translator.translate(get_sentence,
                                                     src= from_lang,
                                                     dest= to_lang)
  translated.append(text_to_translate.text)

translated

df_test_update.insert(0, 'translate', translated, True)

df_test_update

df_test_update.to_csv('/content/drive/MyDrive/machine translation/google translate/spanish.csv')